const dataTxtWeeklyApi = [
    {
      "id": "1",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "1",
      "reference": "Referral program",
      "adURL": "https://bit.ly/35qVQwT",
      "adText": "Hey, we can both earn $10 when you join PayPal and spend $5.",
      "callToAction": "Use my link:",
      "company": "PayPal"
    },
    {
      "id": "2",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "2",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3sFOEWm",
      "adText": "Hey! I've been using Cash App to send money and spend using the Cash Card. Try it using my code <mark>JCMLKKL </mark> and you'll get $5.",
      "callToAction": "Use my link:",
      "company": "CashApp"
    },
    {
      "id": "3",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "3",
      "reference": "Referral program",
      "adURL": "https://bit.ly/36i2N3h",
      "adText": "Hi! 👋 Join me on the SoFi app! Trade stocks, check your credit score for free, and more all in one app. Get $10 (1,000 rewards points) when you sign up using my link—and get 1,000 more points when you check your credit score.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "4",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "4",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3KHBa2A",
      "adText": "Hi! 👋: Join me to start earning more money with SoFi Checking and Savings. You'll earn up to 1.00% APY and pay no account fees. Use my link to sign up and you'll get a $25 bonus and an additional $100 bonus when you set up direct deposit.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "5",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "5",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3JpKx77",
      "adText": "Hey! I'm using SoFi Invest 📊 to buy and sell stocks (and pieces of stocks) with zero fees. Open an Active Investing account with $100 or more, and you'll get $25 in stock. I'll get $50 in stock, too!",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "6",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "6",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3I7XG3c",
      "adText": "Hi! I thought you might want to check out your loan options with SoFi. Learn more and use my link to apply for a SoFi Personal Loan (with $0 fees!) and you can get a $300 welcome bonus.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "7",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "7",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3w1smAH",
      "adText": "Hi! I thought you might want to check out saving on student loans with SoFi. Learn more and use my link to apply for a SoFi Student Loan Refinance and you can get a $300 welcome bonus.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "8",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "8",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3pwcAcM",
      "adText": "I love MoneyGram's easy online transfers & you will too! Use my code <mark>RAFPCM2RN9</mark> for zero fees on your 1st transfer.",
      "callToAction": "Try them at:",
      "company": "MoneyGram"
    },
    {
      "id": "9",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "9",
      "reference": "Referral program",
      "adURL": "https://bit.ly/36LB5fB",
      "adText": "Check out this free app that gets you cash back on gas and other errands! Use promo code <mark>ERIC52748</mark> to get an extra 15¢/gal bonus the first time you make a purchase or ",
      "callToAction": "Use my link:",
      "company": "GetUpside"
    },
    {
      "id": "10",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "10",
      "reference": "Referral program",
      "adURL": "https://bit.ly/36LB5fB",
      "adText": "Earn up to 25¢/gal cash back on gas at stations across the United States – including all the big brands -- PLUS up to 15% on groceries and up to 35% at restaurants.",
      "callToAction": "Use my link:",
      "company": "GetUpside"
    },
    {
      "id": "11",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "11",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3KtPaNB",
      "adText": "Use the promo code <mark>3x48mX</mark> to get 50% off your first month to any unlimited, all-you-can-wash membership with EverWash Car Club.",
      "callToAction": "Use my link:",
      "company": "EverWash"
    },
    {
      "id": "12",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "12",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3IHd4o0",
      "adText": "EverWash partners with your neighborhood's best car washes to bring you unlimited washes for one low monthly price.",
      "callToAction": "Try them at:",
      "company": "EverWash"
    },
    {
      "id": "13",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "13",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3C7CY1Z",
      "adText": "As a Dasher, you can be your own boss and enjoy the flexibility of choosing when, where, and how much you earn. It's that simple.",
      "callToAction": "Try them at:",
      "company": "DoorDash"
    },
    {
      "id": "14",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "14",
      "reference": "Referral program",
      "adURL": "https://bit.ly/35qVQwT",
      "adText": "Hey, we can both earn $10 when you join PayPal and spend $5.",
      "callToAction": "Use my link:",
      "company": "PayPal"
    },
    {
      "id": "15",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "15",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3sFOEWm",
      "adText": "Hey! I've been using Cash App to send money and spend using the Cash Card. Try it using my code <mark>JCMLKKL </mark> and you'll get $5.",
      "callToAction": "Use my link:",
      "company": "CashApp"
    },
    {
      "id": "16",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "16",
      "reference": "Referral program",
      "adURL": "https://bit.ly/36i2N3h",
      "adText": "Hi! 👋 Join me on the SoFi app! Trade stocks, check your credit score for free, and more all in one app. Get $10 (1,000 rewards points) when you sign up using my link—and get 1,000 more points when you check your credit score.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "17",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "17",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3KHBa2A",
      "adText": "Hi! 👋: Join me to start earning more money with SoFi Checking and Savings. You'll earn up to 1.00% APY and pay no account fees. Use my link to sign up and you'll get a $25 bonus and an additional $100 bonus when you set up direct deposit.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "18",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "18",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3JpKx77",
      "adText": "Hey! I'm using SoFi Invest 📊 to buy and sell stocks (and pieces of stocks) with zero fees. Open an Active Investing account with $100 or more, and you'll get $25 in stock. I'll get $50 in stock, too!",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "19",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "19",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3I7XG3c",
      "adText": "Hi! I thought you might want to check out your loan options with SoFi. Learn more and use my link to apply for a SoFi Personal Loan (with $0 fees!) and you can get a $300 welcome bonus.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "20",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "20",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3w1smAH",
      "adText": "Hi! I thought you might want to check out saving on student loans with SoFi. Learn more and use my link to apply for a SoFi Student Loan Refinance and you can get a $300 welcome bonus.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "21",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "21",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3pwcAcM",
      "adText": "I love MoneyGram's easy online transfers & you will too! Use my code <mark>RAFPCM2RN9</mark> for zero fees on your 1st transfer.",
      "callToAction": "Try them at:",
      "company": "MoneyGram"
    },
    {
      "id": "22",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "22",
      "reference": "Referral program",
      "adURL": "https://bit.ly/36LB5fB",
      "adText": "Check out this free app that gets you cash back on gas and other errands! Use promo code <mark>ERIC52748</mark> to get an extra 15¢/gal bonus the first time you make a purchase or ",
      "callToAction": "Use my link:",
      "company": "GetUpside"
    },
    {
      "id": "23",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "23",
      "reference": "Referral program",
      "adURL": "https://bit.ly/36LB5fB",
      "adText": "Earn up to 25¢/gal cash back on gas at stations across the United States – including all the big brands -- PLUS up to 15% on groceries and up to 35% at restaurants.",
      "callToAction": "Use my link:",
      "company": "GetUpside"
    },
    {
      "id": "24",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "24",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3KtPaNB",
      "adText": "Use the promo code <mark>3x48mX</mark> to get 50% off your first month to any unlimited, all-you-can-wash membership with EverWash Car Club.",
      "callToAction": "Use my link:",
      "company": "EverWash"
    },
    {
      "id": "25",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "25",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3IHd4o0",
      "adText": "EverWash partners with your neighborhood's best car washes to bring you unlimited washes for one low monthly price.",
      "callToAction": "Try them at:",
      "company": "EverWash"
    },
    {
      "id": "26",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "26",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3C7CY1Z",
      "adText": "As a Dasher, you can be your own boss and enjoy the flexibility of choosing when, where, and how much you earn. It's that simple.",
      "callToAction": "Try them at:",
      "company": "DoorDash"
    },
    {
      "id": "27",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "27",
      "reference": "Referral program",
      "adURL": "https://bit.ly/35qVQwT",
      "adText": "Hey, we can both earn $10 when you join PayPal and spend $5.",
      "callToAction": "Use my link:",
      "company": "PayPal"
    },
    {
      "id": "28",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "28",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3sFOEWm",
      "adText": "Hey! I've been using Cash App to send money and spend using the Cash Card. Try it using my code <mark>JCMLKKL </mark> and you'll get $5.",
      "callToAction": "Use my link:",
      "company": "CashApp"
    },
    {
      "id": "29",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "29",
      "reference": "Referral program",
      "adURL": "https://bit.ly/36i2N3h",
      "adText": "Hi! 👋 Join me on the SoFi app! Trade stocks, check your credit score for free, and more all in one app. Get $10 (1,000 rewards points) when you sign up using my link—and get 1,000 more points when you check your credit score.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "30",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "30",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3KHBa2A",
      "adText": "Hi! 👋: Join me to start earning more money with SoFi Checking and Savings. You'll earn up to 1.00% APY and pay no account fees. Use my link to sign up and you'll get a $25 bonus and an additional $100 bonus when you set up direct deposit.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "31",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "31",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3JpKx77",
      "adText": "Hey! I'm using SoFi Invest 📊 to buy and sell stocks (and pieces of stocks) with zero fees. Open an Active Investing account with $100 or more, and you'll get $25 in stock. I'll get $50 in stock, too!",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "32",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "32",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3I7XG3c",
      "adText": "Hi! I thought you might want to check out your loan options with SoFi. Learn more and use my link to apply for a SoFi Personal Loan (with $0 fees!) and you can get a $300 welcome bonus.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "33",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "33",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3w1smAH",
      "adText": "Hi! I thought you might want to check out saving on student loans with SoFi. Learn more and use my link to apply for a SoFi Student Loan Refinance and you can get a $300 welcome bonus.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "34",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "34",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3pwcAcM",
      "adText": "I love MoneyGram's easy online transfers & you will too! Use my code <mark>RAFPCM2RN9</mark> for zero fees on your 1st transfer.",
      "callToAction": "Try them at:",
      "company": "MoneyGram"
    },
    {
      "id": "35",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "35",
      "reference": "Referral program",
      "adURL": "https://bit.ly/36LB5fB",
      "adText": "Check out this free app that gets you cash back on gas and other errands! Use promo code <mark>ERIC52748</mark> to get an extra 15¢/gal bonus the first time you make a purchase or ",
      "callToAction": "Use my link:",
      "company": "GetUpside"
    },
    {
      "id": "36",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "36",
      "reference": "Referral program",
      "adURL": "https://bit.ly/36LB5fB",
      "adText": "Earn up to 25¢/gal cash back on gas at stations across the United States – including all the big brands -- PLUS up to 15% on groceries and up to 35% at restaurants.",
      "callToAction": "Use my link:",
      "company": "GetUpside"
    },
    {
      "id": "37",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "37",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3KtPaNB",
      "adText": "Use the promo code <mark>3x48mX</mark> to get 50% off your first month to any unlimited, all-you-can-wash membership with EverWash Car Club.",
      "callToAction": "Use my link:",
      "company": "EverWash"
    },
    {
      "id": "38",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "38",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3IHd4o0",
      "adText": "EverWash partners with your neighborhood's best car washes to bring you unlimited washes for one low monthly price.",
      "callToAction": "Try them at:",
      "company": "EverWash"
    },
    {
      "id": "39",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "39",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3C7CY1Z",
      "adText": "As a Dasher, you can be your own boss and enjoy the flexibility of choosing when, where, and how much you earn. It's that simple.",
      "callToAction": "Try them at:",
      "company": "DoorDash"
    },
    {
      "id": "40",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "40",
      "reference": "Referral program",
      "adURL": "https://bit.ly/35qVQwT",
      "adText": "Hey, we can both earn $10 when you join PayPal and spend $5.",
      "callToAction": "Use my link:",
      "company": "PayPal"
    },
    {
      "id": "41",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "41",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3sFOEWm",
      "adText": "Hey! I've been using Cash App to send money and spend using the Cash Card. Try it using my code <mark>JCMLKKL </mark> and you'll get $5.",
      "callToAction": "Use my link:",
      "company": "CashApp"
    },
    {
      "id": "42",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "42",
      "reference": "Referral program",
      "adURL": "https://bit.ly/36i2N3h",
      "adText": "Hi! 👋 Join me on the SoFi app! Trade stocks, check your credit score for free, and more all in one app. Get $10 (1,000 rewards points) when you sign up using my link—and get 1,000 more points when you check your credit score.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "43",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "43",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3KHBa2A",
      "adText": "Hi! 👋: Join me to start earning more money with SoFi Checking and Savings. You'll earn up to 1.00% APY and pay no account fees. Use my link to sign up and you'll get a $25 bonus and an additional $100 bonus when you set up direct deposit.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "44",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "44",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3JpKx77",
      "adText": "Hey! I'm using SoFi Invest 📊 to buy and sell stocks (and pieces of stocks) with zero fees. Open an Active Investing account with $100 or more, and you'll get $25 in stock. I'll get $50 in stock, too!",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "45",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "45",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3I7XG3c",
      "adText": "Hi! I thought you might want to check out your loan options with SoFi. Learn more and use my link to apply for a SoFi Personal Loan (with $0 fees!) and you can get a $300 welcome bonus.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "46",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "46",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3w1smAH",
      "adText": "Hi! I thought you might want to check out saving on student loans with SoFi. Learn more and use my link to apply for a SoFi Student Loan Refinance and you can get a $300 welcome bonus.",
      "callToAction": "Use my link:",
      "company": "SoFi"
    },
    {
      "id": "47",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "47",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3pwcAcM",
      "adText": "I love MoneyGram's easy online transfers & you will too! Use my code <mark>RAFPCM2RN9</mark> for zero fees on your 1st transfer.",
      "callToAction": "Try them at:",
      "company": "MoneyGram"
    },
    {
      "id": "48",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "48",
      "reference": "Referral program",
      "adURL": "https://bit.ly/36LB5fB",
      "adText": "Check out this free app that gets you cash back on gas and other errands! Use promo code <mark>ERIC52748</mark> to get an extra 15¢/gal bonus the first time you make a purchase or ",
      "callToAction": "Use my link:",
      "company": "GetUpside"
    },
    {
      "id": "49",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "49",
      "reference": "Referral program",
      "adURL": "https://bit.ly/36LB5fB",
      "adText": "Earn up to 25¢/gal cash back on gas at stations across the United States – including all the big brands -- PLUS up to 15% on groceries and up to 35% at restaurants.",
      "callToAction": "Use my link:",
      "company": "GetUpside"
    },
    {
      "id": "50",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "50",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3KtPaNB",
      "adText": "Use the promo code <mark>3x48mX</mark> to get 50% off your first month to any unlimited, all-you-can-wash membership with EverWash Car Club.",
      "callToAction": "Use my link:",
      "company": "EverWash"
    },
    {
      "id": "51",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "51",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3IHd4o0",
      "adText": "EverWash partners with your neighborhood's best car washes to bring you unlimited washes for one low monthly price.",
      "callToAction": "Try them at:",
      "company": "EverWash"
    },
    {
      "id": "52",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "52",
      "reference": "Referral program",
      "adURL": "https://bit.ly/3C7CY1Z",
      "adText": "As a Dasher, you can be your own boss and enjoy the flexibility of choosing when, where, and how much you earn. It's that simple.",
      "callToAction": "Try them at:",
      "company": "DoorDash"
    },
    {
      "id": "53",
      "created_on": "11/23/2022",
      "category": "weekNumber",
      "frequency": "53",
      "reference": "Referral program",
      "adURL": "https://bit.ly/35qVQwT",
      "adText": "Hey, we can both earn $10 when you join PayPal and spend $5.",
      "callToAction": "Use my link:",
      "company": "PayPal"
    }
  ]
module.exports = dataTxtWeeklyApi;